"""Database helpers for local SQLite or Supabase Postgres."""

from __future__ import annotations

import os
from datetime import date
from functools import lru_cache
from pathlib import Path
from typing import Any, Iterable

import pandas as pd
from sqlalchemy import create_engine, event, text
from sqlalchemy.engine import Engine
from sqlalchemy.exc import IntegrityError, SQLAlchemyError

BASE_DIR = Path(__file__).resolve().parents[1]
DATA_DIR = BASE_DIR / "data"
DB_PATH = DATA_DIR / "football.db"


def _sqlite_url() -> str:
    """Return a SQLAlchemy URL for the local development database."""
    return f"sqlite:///{DB_PATH.as_posix()}"


def _read_database_url_from_secrets() -> str | None:
    """Read the deployment database URL from Streamlit secrets if present."""
    try:
        import streamlit as st

        database = st.secrets.get("database", {})
        return database.get("url") if database else None
    except (FileNotFoundError, KeyError):
        return None


def _normalise_database_url(url: str) -> str:
    """Prefer psycopg 3 when a plain Postgres URL is supplied."""
    if url.startswith("postgresql://"):
        return url.replace("postgresql://", "postgresql+psycopg://", 1)
    if url.startswith("postgres://"):
        return url.replace("postgres://", "postgresql+psycopg://", 1)
    return url


def get_database_url() -> str:
    """Return the configured database URL, falling back to local SQLite."""
    url = os.getenv("FOOTBALL_APP_DATABASE_URL") or _read_database_url_from_secrets()
    return _normalise_database_url(url) if url else _sqlite_url()


@lru_cache(maxsize=1)
def get_engine() -> Engine:
    """Create one SQLAlchemy engine per process."""
    url = get_database_url()
    connect_args: dict[str, Any] = {}

    if url.startswith("sqlite"):
        DATA_DIR.mkdir(parents=True, exist_ok=True)
        connect_args["check_same_thread"] = False

    engine = create_engine(url, connect_args=connect_args, future=True)

    if engine.dialect.name == "sqlite":
        event.listen(engine, "connect", _enable_sqlite_foreign_keys)

    return engine


def _enable_sqlite_foreign_keys(dbapi_connection: Any, _connection_record: Any) -> None:
    """Enable foreign-key checks for each SQLite connection."""
    cursor = dbapi_connection.cursor()
    cursor.execute("PRAGMA foreign_keys = ON;")
    cursor.close()


def get_database_label() -> str:
    """Return a safe database label for the sidebar."""
    engine = get_engine()
    if engine.dialect.name == "sqlite":
        return str(Path(engine.url.database or DB_PATH))
    if engine.dialect.name == "postgresql":
        return "Supabase/Postgres from Streamlit secrets"
    return engine.dialect.name


def _is_postgres() -> bool:
    """Check whether the active database is PostgreSQL."""
    return get_engine().dialect.name == "postgresql"


def init_db() -> None:
    """Create database tables if they do not already exist."""
    statements = _postgres_schema() if _is_postgres() else _sqlite_schema()
    with get_engine().begin() as connection:
        for statement in statements:
            connection.execute(text(statement))


def _sqlite_schema() -> list[str]:
    """SQLite schema for local development."""
    return [
        """
        CREATE TABLE IF NOT EXISTS players (
            player_id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL UNIQUE,
            primary_position TEXT NOT NULL,
            secondary_position TEXT,
            preferred_role TEXT,
            active INTEGER DEFAULT 1,
            games_played INTEGER DEFAULT 0,
            starts INTEGER DEFAULT 0,
            subs INTEGER DEFAULT 0,
            minutes_played INTEGER DEFAULT 0,
            last_played TEXT,
            consecutive_sitouts INTEGER DEFAULT 0
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS matches (
            match_id INTEGER PRIMARY KEY AUTOINCREMENT,
            match_date TEXT NOT NULL,
            opponent TEXT,
            venue TEXT,
            status TEXT DEFAULT 'planned'
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS match_players (
            match_player_id INTEGER PRIMARY KEY AUTOINCREMENT,
            match_id INTEGER NOT NULL,
            player_id INTEGER NOT NULL,
            role TEXT NOT NULL,
            available INTEGER DEFAULT 1,
            minutes INTEGER DEFAULT 0,
            FOREIGN KEY(match_id) REFERENCES matches(match_id),
            FOREIGN KEY(player_id) REFERENCES players(player_id),
            UNIQUE(match_id, player_id)
        );
        """,
    ]


def _postgres_schema() -> list[str]:
    """Postgres schema for Supabase deployment."""
    return [
        """
        CREATE TABLE IF NOT EXISTS players (
            player_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL UNIQUE,
            primary_position TEXT NOT NULL,
            secondary_position TEXT,
            preferred_role TEXT,
            active INTEGER DEFAULT 1,
            games_played INTEGER DEFAULT 0,
            starts INTEGER DEFAULT 0,
            subs INTEGER DEFAULT 0,
            minutes_played INTEGER DEFAULT 0,
            last_played TEXT,
            consecutive_sitouts INTEGER DEFAULT 0
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS matches (
            match_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            match_date TEXT NOT NULL,
            opponent TEXT,
            venue TEXT,
            status TEXT DEFAULT 'planned'
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS match_players (
            match_player_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            match_id INTEGER NOT NULL REFERENCES matches(match_id),
            player_id INTEGER NOT NULL REFERENCES players(player_id),
            role TEXT NOT NULL,
            available INTEGER DEFAULT 1,
            minutes INTEGER DEFAULT 0,
            UNIQUE(match_id, player_id)
        );
        """,
    ]


def _date_to_text(value: date | str) -> str:
    """Convert Python date objects into ISO text for storage."""
    if isinstance(value, date):
        return value.isoformat()
    return str(value)


def fetch_dataframe(query: str, params: dict[str, Any] | None = None) -> pd.DataFrame:
    """Run a SELECT query and return a pandas dataframe."""
    with get_engine().connect() as connection:
        return pd.read_sql_query(text(query), connection, params=params or {})


def get_players(include_inactive: bool = True) -> pd.DataFrame:
    """Return players ordered by active status and name."""
    where_clause = "" if include_inactive else "WHERE active = 1"
    return fetch_dataframe(
        f"""
        SELECT
            player_id,
            name,
            primary_position,
            secondary_position,
            preferred_role,
            active,
            games_played,
            starts,
            subs,
            minutes_played,
            last_played,
            consecutive_sitouts
        FROM players
        {where_clause}
        ORDER BY active DESC, LOWER(name);
        """
    )


def add_player(
    name: str,
    primary_position: str,
    secondary_position: str | None,
    preferred_role: str,
    active: bool,
) -> tuple[bool, str]:
    """Insert a player and return a user-facing result message."""
    try:
        with get_engine().begin() as connection:
            connection.execute(
                text(
                    """
                    INSERT INTO players (
                        name,
                        primary_position,
                        secondary_position,
                        preferred_role,
                        active
                    )
                    VALUES (
                        :name,
                        :primary_position,
                        :secondary_position,
                        :preferred_role,
                        :active
                    );
                    """
                ),
                {
                    "name": name,
                    "primary_position": primary_position,
                    "secondary_position": secondary_position,
                    "preferred_role": preferred_role,
                    "active": int(active),
                },
            )
        return True, f"Added {name}."
    except IntegrityError:
        return False, f"A player named {name} already exists."
    except SQLAlchemyError as error:
        return False, f"Could not add player: {error}"


def update_player(
    player_id: int,
    name: str,
    primary_position: str,
    secondary_position: str | None,
    preferred_role: str,
    active: bool,
) -> tuple[bool, str]:
    """Update editable player details."""
    try:
        with get_engine().begin() as connection:
            result = connection.execute(
                text(
                    """
                    UPDATE players
                    SET
                        name = :name,
                        primary_position = :primary_position,
                        secondary_position = :secondary_position,
                        preferred_role = :preferred_role,
                        active = :active
                    WHERE player_id = :player_id;
                    """
                ),
                {
                    "name": name,
                    "primary_position": primary_position,
                    "secondary_position": secondary_position,
                    "preferred_role": preferred_role,
                    "active": int(active),
                    "player_id": int(player_id),
                },
            )
        if result.rowcount == 0:
            return False, "Player not found."
        return True, f"Updated {name}."
    except IntegrityError:
        return False, f"A player named {name} already exists."
    except SQLAlchemyError as error:
        return False, f"Could not update player: {error}"


def delete_player(player_id: int) -> tuple[bool, str]:
    """Delete a player, or deactivate them if they have match history."""
    try:
        with get_engine().begin() as connection:
            history_count = connection.execute(
                text("SELECT COUNT(*) FROM match_players WHERE player_id = :player_id;"),
                {"player_id": int(player_id)},
            ).scalar_one()

            if history_count:
                connection.execute(
                    text("UPDATE players SET active = 0 WHERE player_id = :player_id;"),
                    {"player_id": int(player_id)},
                )
                return True, "Player has match history, so they were set inactive instead."

            result = connection.execute(
                text("DELETE FROM players WHERE player_id = :player_id;"),
                {"player_id": int(player_id)},
            )
        if result.rowcount == 0:
            return False, "Player not found."
        return True, "Player deleted."
    except SQLAlchemyError as error:
        return False, f"Could not delete player: {error}"


def save_match_selection(
    match_date: date | str,
    opponent: str | None,
    venue: str | None,
    active_player_ids: Iterable[int],
    available_player_ids: Iterable[int],
    starter_ids: Iterable[int],
    substitute_ids: Iterable[int],
) -> tuple[bool, str, int | None]:
    """Create a match and save every active player's match role."""
    active_id_set = {int(player_id) for player_id in active_player_ids}
    available_id_set = {int(player_id) for player_id in available_player_ids}
    starter_id_set = {int(player_id) for player_id in starter_ids}
    substitute_id_set = {int(player_id) for player_id in substitute_ids}

    try:
        with get_engine().begin() as connection:
            if _is_postgres():
                result = connection.execute(
                    text(
                        """
                        INSERT INTO matches (match_date, opponent, venue, status)
                        VALUES (:match_date, :opponent, :venue, 'planned')
                        RETURNING match_id;
                        """
                    ),
                    {
                        "match_date": _date_to_text(match_date),
                        "opponent": opponent,
                        "venue": venue,
                    },
                )
                match_id = int(result.scalar_one())
            else:
                result = connection.execute(
                    text(
                        """
                        INSERT INTO matches (match_date, opponent, venue, status)
                        VALUES (:match_date, :opponent, :venue, 'planned');
                        """
                    ),
                    {
                        "match_date": _date_to_text(match_date),
                        "opponent": opponent,
                        "venue": venue,
                    },
                )
                match_id = int(result.lastrowid)

            rows = []
            for player_id in sorted(active_id_set):
                if player_id in starter_id_set:
                    role = "starter"
                    available = 1
                elif player_id in substitute_id_set:
                    role = "substitute"
                    available = 1
                elif player_id in available_id_set:
                    role = "sit_out"
                    available = 1
                else:
                    role = "unavailable"
                    available = 0

                rows.append(
                    {
                        "match_id": match_id,
                        "player_id": player_id,
                        "role": role,
                        "available": available,
                        "minutes": 0,
                    }
                )

            connection.execute(
                text(
                    """
                    INSERT INTO match_players (
                        match_id,
                        player_id,
                        role,
                        available,
                        minutes
                    )
                    VALUES (
                        :match_id,
                        :player_id,
                        :role,
                        :available,
                        :minutes
                    );
                    """
                ),
                rows,
            )
        return True, f"Saved match #{match_id}.", match_id
    except SQLAlchemyError as error:
        return False, f"Could not save match: {error}", None


def get_matches(status: str | None = None) -> pd.DataFrame:
    """Return matches with simple selection counts."""
    params: dict[str, Any] = {}
    where_clause = ""
    if status:
        where_clause = "WHERE m.status = :status"
        params["status"] = status

    return fetch_dataframe(
        f"""
        SELECT
            m.match_id,
            m.match_date,
            m.opponent,
            m.venue,
            m.status,
            COALESCE(SUM(CASE WHEN mp.role = 'starter' THEN 1 ELSE 0 END), 0) AS starters,
            COALESCE(SUM(CASE WHEN mp.role = 'substitute' THEN 1 ELSE 0 END), 0) AS substitutes,
            COALESCE(SUM(CASE WHEN mp.role = 'sit_out' THEN 1 ELSE 0 END), 0) AS sit_outs,
            COALESCE(SUM(CASE WHEN mp.available = 1 THEN 1 ELSE 0 END), 0) AS available_players
        FROM matches m
        LEFT JOIN match_players mp ON m.match_id = mp.match_id
        {where_clause}
        GROUP BY
            m.match_id,
            m.match_date,
            m.opponent,
            m.venue,
            m.status
        ORDER BY m.match_date DESC, m.match_id DESC;
        """,
        params,
    )


def get_match_details(match_id: int) -> dict[str, Any] | None:
    """Return one match row as a dictionary."""
    with get_engine().connect() as connection:
        row = connection.execute(
            text(
                """
                SELECT match_id, match_date, opponent, venue, status
                FROM matches
                WHERE match_id = :match_id;
                """
            ),
            {"match_id": int(match_id)},
        ).mappings().first()
    return dict(row) if row else None


def get_match_players(match_id: int) -> pd.DataFrame:
    """Return all player rows saved for one match."""
    return fetch_dataframe(
        """
        SELECT
            mp.match_player_id,
            mp.match_id,
            mp.player_id,
            p.name,
            p.primary_position,
            p.secondary_position,
            p.preferred_role,
            mp.role,
            mp.available,
            mp.minutes
        FROM match_players mp
        JOIN players p ON mp.player_id = p.player_id
        WHERE mp.match_id = :match_id
        ORDER BY
            CASE mp.role
                WHEN 'starter' THEN 1
                WHEN 'substitute' THEN 2
                WHEN 'sit_out' THEN 3
                ELSE 4
            END,
            LOWER(p.name);
        """,
        {"match_id": int(match_id)},
    )


def complete_match_update(
    match_id: int,
    minutes_by_player: dict[int, int],
) -> tuple[bool, str]:
    """Apply post-match minutes and update player rotation statistics once."""
    try:
        with get_engine().begin() as connection:
            match = connection.execute(
                text("SELECT match_date, status FROM matches WHERE match_id = :match_id;"),
                {"match_id": int(match_id)},
            ).mappings().first()
            if not match:
                return False, "Match not found."
            if match["status"] == "completed":
                return False, "This match is already completed, so stats were not updated again."

            rows = connection.execute(
                text(
                    """
                    SELECT player_id, role, available
                    FROM match_players
                    WHERE match_id = :match_id;
                    """
                ),
                {"match_id": int(match_id)},
            ).mappings().all()
            if not rows:
                return False, "No players are saved for this match."

            clean_minutes: dict[int, int] = {}
            for row in rows:
                player_id = int(row["player_id"])
                role = row["role"]
                minutes = int(minutes_by_player.get(player_id, 0))
                if minutes < 0 or minutes > 120:
                    return False, "Minutes must be between 0 and 120."
                if role == "starter" and minutes <= 0:
                    return False, "Starters must have minutes greater than 0."
                clean_minutes[player_id] = minutes

            match_date = match["match_date"]

            for row in rows:
                player_id = int(row["player_id"])
                role = row["role"]
                available = int(row["available"])
                minutes = clean_minutes.get(player_id, 0)

                if role in {"starter", "substitute"}:
                    connection.execute(
                        text(
                            """
                            UPDATE match_players
                            SET minutes = :minutes
                            WHERE match_id = :match_id AND player_id = :player_id;
                            """
                        ),
                        {
                            "minutes": minutes,
                            "match_id": int(match_id),
                            "player_id": player_id,
                        },
                    )

                if role == "starter":
                    connection.execute(
                        text(
                            """
                            UPDATE players
                            SET
                                games_played = games_played + 1,
                                starts = starts + 1,
                                minutes_played = minutes_played + :minutes,
                                last_played = :last_played,
                                consecutive_sitouts = 0
                            WHERE player_id = :player_id;
                            """
                        ),
                        {
                            "minutes": minutes,
                            "last_played": match_date,
                            "player_id": player_id,
                        },
                    )
                elif role == "substitute" and minutes > 0:
                    connection.execute(
                        text(
                            """
                            UPDATE players
                            SET
                                games_played = games_played + 1,
                                subs = subs + 1,
                                minutes_played = minutes_played + :minutes,
                                last_played = :last_played,
                                consecutive_sitouts = 0
                            WHERE player_id = :player_id;
                            """
                        ),
                        {
                            "minutes": minutes,
                            "last_played": match_date,
                            "player_id": player_id,
                        },
                    )
                elif role == "sit_out" and available:
                    connection.execute(
                        text(
                            """
                            UPDATE players
                            SET consecutive_sitouts = consecutive_sitouts + 1
                            WHERE player_id = :player_id;
                            """
                        ),
                        {"player_id": player_id},
                    )

            connection.execute(
                text("UPDATE matches SET status = 'completed' WHERE match_id = :match_id;"),
                {"match_id": int(match_id)},
            )
        return True, "Post-match stats updated."
    except SQLAlchemyError as error:
        return False, f"Could not update match: {error}"
