CREATE TABLE IF NOT EXISTS players (
    player_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    primary_position TEXT NOT NULL,
    secondary_position TEXT,
    preferred_role TEXT,
    active INTEGER DEFAULT 1,
    games_played INTEGER DEFAULT 0,
    starts INTEGER DEFAULT 0,
    subs INTEGER DEFAULT 0,
    minutes_played INTEGER DEFAULT 0,
    last_played TEXT,
    consecutive_sitouts INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS matches (
    match_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_date TEXT NOT NULL,
    opponent TEXT,
    venue TEXT,
    status TEXT DEFAULT 'planned'
);

CREATE TABLE IF NOT EXISTS match_players (
    match_player_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id INTEGER NOT NULL REFERENCES matches(match_id),
    player_id INTEGER NOT NULL REFERENCES players(player_id),
    role TEXT NOT NULL,
    available INTEGER DEFAULT 1,
    minutes INTEGER DEFAULT 0,
    UNIQUE(match_id, player_id)
);
